cache:
  apt: true
install:
- pip3 install git+https://github.com/mesonbuild/meson.git
- meson --version
- wget -c https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
- unzip ninja-linux.zip -d ${HOME}/bin
- PATH=${HOME}/bin:$PATH
- ninja --version
language: python
matrix:
  include:
  - addons:
      apt:
        packages:
        - qtbase5-dev
        - libvncserver-dev
        - ninja-build
    env:
    - NAME=aqemu
    - REPO=https://github.com/tobimensch/aqemu
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - libgtk-3-dev
        - libxkbfile-dev
        - libpulse-dev
        - gobject-introspection
        - libgirepository1.0-dev
        - ninja-build
    env:
    - NAME=cinnamon-desktop
    - REPO=https://github.com/linuxmint/cinnamon-desktop
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=dpdk
    - REPO=git://dpdk.org/dpdk
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=graphene
    - REPO=git://github.com/ebassi/graphene
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=gstreamer
    - REPO=git://anongit.freedesktop.org/gstreamer/gstreamer/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - libgirepository1.0-dev
        - libgtk-3-dev
        - ninja-build
    env:
    - NAME=hardcode-tray
    - REPO=https://github.com/bil-elmoussaoui/Hardcode-Tray
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - libproxy-dev
        - libcanberra-dev
        - libdbus-glib-1-dev
        - libgtk2.0-dev
        - libnotify-dev
        - libluajit-5.1-dev
        - libperl-dev
        - ninja-build
    env:
    - NAME=hexchat
    - REPO=https://github.com/hexchat/hexchat
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=jsoncpp
    - REPO=https://github.com/open-source-parsers/jsoncpp
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=ksh
    - REPO=https://github.com/att/ast
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - libpciaccess-dev
        - ninja-build
    env:
    - NAME=libdrm
    - REPO=git://anongit.freedesktop.org/drm/libdrm/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=libepoxy
    - REPO=https://github.com/anholt/libepoxy/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=libfuse
    - REPO=https://github.com/libfuse/libfuse
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - valac
        - libjson-glib-dev
        - libsoup2.4-dev
        - libgee-0.8-dev
        - libarchive-dev
        - gobject-introspection
        - ninja-build
    env:
    - NAME=libhttpseverywhere
    - REPO=https://git.gnome.org/browse/libhttpseverywhere
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=libosmscout
    - REPO=https://github.com/Framstag/libosmscout
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=libva
    - REPO=https://github.com/intel/libva
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=orc
    - REPO=git://anongit.freedesktop.org/gstreamer/orc/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - libxml2-dev
        - ninja-build
    env:
    - NAME=outlier
    - REPO=https://github.com/kerolasa/outlier
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=parzip
    - REPO=https://github.com/jpakkane/parzip
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=pithos
    - REPO=https://github.com/pithos/pithos
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=szl
    - REPO=https://github.com/dimkr/szl
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="git submodule update --init"
  - addons:
      apt:
        packages:
        - valac
        - libsoup2.4-dev
        - ninja-build
    env:
    - NAME=valum
    - REPO=https://github.com/valum-framework/valum
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - addons:
      apt:
        packages:
        - ninja-build
    env:
    - NAME=zstandard
    - REPO=https://github.com/facebook/zstd.git
    - BRANCH=master
    - SOURCEDIR=contrib/meson
    - HACKS="true"
python: 3.6
script:
- git clone --depth=50 --branch ${BRANCH} ${REPO} ${NAME}
- cd ${NAME}
- eval ${HACKS}
- meson _build ${SOURCEDIR}

