cache:
  apt: true
install:
- docker pull jturney/mesoncorpusci
language: python
matrix:
  include:
  - env:
    - NAME=aqemu
    - REPO=https://github.com/tobimensch/aqemu
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=cinnamon-desktop
    - REPO=https://github.com/linuxmint/cinnamon-desktop
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=dpdk
    - REPO=git://dpdk.org/dpdk
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=graphene
    - REPO=git://github.com/ebassi/graphene
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=gstreamer
    - REPO=git://anongit.freedesktop.org/gstreamer/gstreamer/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=hardcode-tray
    - REPO=https://github.com/bil-elmoussaoui/Hardcode-Tray
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=hexchat
    - REPO=https://github.com/hexchat/hexchat
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=jsoncpp
    - REPO=https://github.com/open-source-parsers/jsoncpp
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=ksh
    - REPO=https://github.com/att/ast
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=libdrm
    - REPO=git://anongit.freedesktop.org/drm/libdrm/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=libepoxy
    - REPO=https://github.com/anholt/libepoxy/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=libfuse
    - REPO=https://github.com/libfuse/libfuse
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=libhttpseverywhere
    - REPO=https://git.gnome.org/browse/libhttpseverywhere
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=libosmscout
    - REPO=https://github.com/Framstag/libosmscout
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=libva
    - REPO=https://github.com/intel/libva
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=orc
    - REPO=git://anongit.freedesktop.org/gstreamer/orc/
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=outlier
    - REPO=https://github.com/kerolasa/outlier
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=parzip
    - REPO=https://github.com/jpakkane/parzip
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=pithos
    - REPO=https://github.com/pithos/pithos
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=szl
    - REPO=https://github.com/dimkr/szl
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="git submodule update --init"
  - env:
    - NAME=valum
    - REPO=https://github.com/valum-framework/valum
    - BRANCH=master
    - SOURCEDIR=.
    - HACKS="true"
  - env:
    - NAME=zstandard
    - REPO=https://github.com/facebook/zstd.git
    - BRANCH=master
    - SOURCEDIR=contrib/meson
    - HACKS="true"
python: 3.6
script:
- 'docker run jturney/mesoncorpusci /bin/sh -c " pip3 install git+https://github.com/mesonbuild/meson.git
  && git clone --depth=50 --branch ${BRANCH} ${REPO} ${NAME} && cd ${NAME} && eval
  ${HACKS} && meson _build ${SOURCEDIR}" '
services:
- docker

