before_script:
- touch script
- echo "chronic apt-get -y update &&" >>script
- if test -n "${BUILDDEP}" ; then echo "chronic apt-get -y build-dep ${BUILDDEP} &&" >>script ; fi
- if test -n "${ALSOINSTALL}" ; then echo "chronic apt-get -y install ${ALSOINSTALL} &&" >>script ; fi
- if test -z "${MESON_COMMIT}" ; then echo "retry -- pip3 install git+https://github.com/mesonbuild/meson.git &&" >>script ; fi
- if test -n "${MESON_COMMIT}" ; then echo "retry -- git clone https://github.com/mesonbuild/meson.git && retry -- git -C meson fetch
  origin ${MESON_COMMIT} && git -C meson checkout FETCH_HEAD && pip3 install ./meson &&" >>script ; fi
- if test -n "${COMMIT}" ; then echo "retry -- git clone ${REPO} ${NAME} && git -C ${NAME} checkout ${COMMIT} &&" >>script ; fi
- if test -z "${COMMIT}" ; then echo "retry -- git clone --depth=1 --branch ${BRANCH:-master} ${REPO} ${NAME} &&" >>script ; fi
- echo "cd ${NAME} && " >>script
- if test -n "${HACKS}" ; then echo "${HACKS} &&" >>script ; fi
- echo "meson _build ${SOURCEDIR} ${CONFIG} &&" >>script
- if test -n "${BUILD}" ; then echo "DESTDIR=/install ninja -C _build ${BUILD}" >>script ; fi
- if test -z "${BUILD}" ; then echo "true" >>script ; fi
cache:
  apt: true
install:
- docker pull jturney/mesoncorpusci
language: python
matrix:
  include:
  - env:
    - NAME=aqemu
    - REPO=https://github.com/tobimensch/aqemu
    - BUILDDEP=aqemu
    - BUILD="all install"
  - env:
    - NAME=bolt
    - REPO=https://gitlab.freedesktop.org/bolt/bolt
    - ALSOINSTALL="libglib2.0-dev libudev-dev udev libpolkit-gobject-1-dev systemd libsystemd-dev"
    - BUILD="all install"
  - env:
    - NAME=budgie-desktop
    - REPO=https://github.com/budgie-desktop/budgie-desktop
    - ALSOINSTALL="valac libgtk-3-dev libwnck-3-dev libpeas-dev uuid-dev libibus-1.0-dev libgnome-desktop-3-dev libaccountsservice-dev
      intltool libpulse-dev sassc libpolkit-agent-1-dev libmutter-2-dev libgnome-menu-3-dev libupower-glib-dev libgnome-bluetooth-dev
      gtk-doc-tools gnome-settings-daemon-dev"
  - env:
    - NAME=casync
    - REPO=https://github.com/systemd/casync
    - BUILDDEP=casync
    - ALSOINSTALL="libudev-dev"
    - BUILD="all install"
  - env:
    - NAME=cinnamon-desktop
    - REPO=https://github.com/linuxmint/cinnamon-desktop
    - BUILDDEP=cinnamon-desktop
    - BUILD="all install"
  - env:
    - NAME=dbus-broker
    - REPO=https://github.com/bus1/dbus-broker
    - ALSOINSTALL="python-docutils libdbus-1-dev libglib2.0-dev libsystemd-dev systemd"
    - BUILD="all install"
  - env:
    - NAME=dpdk
    - REPO=git://dpdk.org/dpdk
  - env:
    - NAME=emeus
    - REPO=https://github.com/ebassi/emeus
    - ALSOINSTALL="libglib2.0-dev libgtk-3-dev libgirepository1.0-dev"
  - env:
    - NAME=fwupd
    - REPO=https://github.com/hughsie/fwupd
    - COMMIT=cff980cfda882939b5a3a5c2baadb657d5dbb051
    - BUILDDEP=fwupd
    - ALSOINSTALL="gnu-efi libjson-glib-dev help2man valac"
    - BUILD="all install"
  - env:
    - NAME=geary
    - REPO=https://git.gnome.org/browse/geary
    - BUILDDEP=geary
    - ALSOINSTALL="libunwind-dev libgoa-1.0-dev itstool libjson-glib-dev"
    - BUILD="all install"
  - env:
    - NAME=glib
    - REPO=https://gitlab.gnome.org/GNOME/glib
    - BUILDDEP=glib2.0
  - env:
    - NAME=gnome-boxes
    - REPO=https://gitlab.gnome.org/GNOME/gnome-boxes
    - BRANCH=v3.31.1
    - BUILDDEP=gnome-boxes
    - ALSOINSTALL="libwebkit2gtk-4.0-dev freerdp2-dev"
    - BUILD="all install"
  - env:
    - NAME=gnome-builder
    - REPO=https://gitlab.gnome.org/GNOME/gnome-builder
    - BRANCH=3.28.3
    - BUILDDEP=gnome-builder
    - CONFIG="-Dwith_spellcheck=false"
  - env:
    - NAME=gnome-mpv
    - REPO=https://github.com/gnome-mpv/gnome-mpv
    - BUILDDEP=gnome-mpv
    - BUILD="all install"
  - env:
    - NAME=gnome-recipes
    - REPO=https://gitlab.gnome.org/GNOME/recipes
    - BUILDDEP=gnome-recipes
    - ALSOINSTALL="libgoa-1.0-dev libjson-glib-dev"
    - BUILD="all install"
  - env:
    - NAME=gnome-software
    - REPO=https://gitlab.gnome.org/GNOME/gnome-software
    - COMMIT=12031b42109892e50b38f4037b923335fdfb0fd0
    - BUILDDEP=gnome-software
    - BUILD="all install"
  - env:
    - NAME=gnome-twitch
    - REPO=https://github.com/vinszent/gnome-twitch
    - BUILDDEP=gnome-twitch
  - env:
    - NAME=gnome-usage
    - REPO=https://gitlab.gnome.org/GNOME/gnome-usage
    - ALSOINSTALL="libaccountsservice-dev libgtk-3-dev libgtop2-dev valac"
    - BUILD="all install"
  - env:
    - NAME=graphene
    - REPO=git://github.com/ebassi/graphene
    - BUILDDEP=graphene
    - BUILD="all install"
  - env:
    - NAME=grilo
    - REPO=https://git.gnome.org/browse/grilo
    - BUILDDEP=grilo
    - BUILD="all install"
  - env:
    - NAME=grilo-plugins
    - REPO=https://git.gnome.org/browse/grilo-plugins
    - COMMIT=770b11088c1b99ec979015faf95078c1e0dfe69e
    - BUILDDEP=grilo-plugins
    - BUILD="all install"
  - env:
    - NAME=gstreamer
    - REPO=git://anongit.freedesktop.org/gstreamer/gstreamer/
    - BUILDDEP=gstreamer1.0
    - BUILD="all"
  - env:
    - NAME=gtk+
    - REPO=https://gitlab.gnome.org/GNOME/gtk
    - COMMIT=894a0c0f
    - BUILDDEP=libgtk-3-dev
  - env:
    - NAME=gtkdapp
    - REPO=https://gitlab.com/csoriano/GtkDApp
    - ALSOINSTALL="libgtkd-3-dev gdc gsettings-desktop-schemas-dev libglib2.0-dev gettext"
  - env:
    - NAME=gvfs
    - REPO=https://git.gnome.org/browse/gvfs/
    - COMMIT=3a7bb06be72fc62b4ec524afe67febf0f529066d
    - BUILDDEP=gvfs
    - ALSOINSTALL="libbluray-dev libnfs-dev"
    - BUILD="all install"
  - env:
    - NAME=hardcode-tray
    - REPO=https://github.com/bil-elmoussaoui/Hardcode-Tray
    - ALSOINSTALL="libgirepository1.0-dev libgtk-3-dev"
    - BUILD="all install"
  - env:
    - NAME=hexchat
    - REPO=https://github.com/hexchat/hexchat
    - BUILDDEP=hexchat
    - ALSOINSTALL="libluajit-5.1-dev"
    - BUILD="all install"
  - env:
    - NAME=igt
    - REPO=git://anongit.freedesktop.org/xorg/app/intel-gpu-tools/
    - BUILDDEP=intel-gpu-tools
    - ALSOINSTALL="libssl-dev libdw-dev"
    - BUILD="all install"
  - env:
    - NAME=json-glib
    - REPO=https://gitlab.gnome.org/GNOME/json-glib
    - BUILDDEP=json-glib
    - BUILD="all install"
  - env:
    - NAME=jsoncpp
    - REPO=https://github.com/open-source-parsers/jsoncpp
    - BUILD="all install"
  - env:
    - NAME=ksh
    - REPO=https://github.com/att/ast
    - BUILDDEP=ksh
    - BUILD="all install"
  - env:
    - NAME=libdrm
    - REPO=git://anongit.freedesktop.org/drm/libdrm/
    - BUILDDEP=libdrm
    - BUILD="all install"
  - env:
    - NAME=libepoxy
    - REPO=https://github.com/anholt/libepoxy/
    - BUILDDEP=libepoxy
  - env:
    - NAME=libfuse
    - REPO=https://github.com/libfuse/libfuse
    - BUILDDEP=fuse
    - ALSOINSTALL="udev"
    - BUILD="all install"
  - env:
    - NAME=libgit2-glib
    - REPO=https://git.gnome.org/browse/libgit2-glib
    - BUILDDEP=libgit2-glib
    - ALSOINSTALL="python-gi-dev"
    - BUILD="all install"
  - env:
    - NAME=libhttpseverywhere
    - REPO=https://git.gnome.org/browse/libhttpseverywhere
    - ALSOINSTALL="valac libjson-glib-dev libsoup2.4-dev libgee-0.8-dev libarchive-dev gobject-introspection"
  - env:
    - NAME=libmodulemd
    - REPO=https://github.com/fedora-modularity/libmodulemd
    - ALSOINSTALL="clang-format gobject-introspection gtk-doc-tools libgirepository1.0-dev libglib2.0-dev libyaml-dev python-autopep8
      valgrind"
    - BUILD="all install"
    - HACKS='sed -i s!usr/bin/sh!bin/sh! spec_tmpl.sh'
  - env:
    - NAME=libosmscout
    - REPO=https://github.com/Framstag/libosmscout
    - BUILD="all install"
  - env:
    - NAME=libspng
    - REPO=https://gitlab.com/randy408/libspng
    - ALSOINSTALL="zlib1g-dev libpng-dev"
    - BUILD="all install"
  - env:
    - NAME=libva
    - REPO=https://github.com/intel/libva
    - BUILDDEP=libva
    - BUILD="all install"
  - env:
    - NAME=libzim
    - REPO=https://github.com/openzim/libzim
    - BUILDDEP=zimlib
    - BUILD="all install"
  - env:
    - NAME=lightdm-webkit2-greeter
    - REPO=https://github.com/Antergos/lightdm-webkit2-greeter
    - BRANCH=stable
    - ALSOINSTALL="libdbus-glib-1-dev liblightdm-gobject-1-dev libgtk-3-dev libwebkit2gtk-4.0-dev"
    - BUILD="all install"
  - env:
    - NAME=mesa
    - REPO=git://anongit.freedesktop.org/mesa/mesa/
    - COMMIT=cb03803253b026d5f4c1e0fef431a12df461e6d8
    - BUILDDEP=mesa
    - ALSOINSTALL="libegl1-mesa-dev libxvmc-dev"
  - env:
    - NAME=miraclecast
    - REPO=https://github.com/albfan/miraclecast
    - ALSOINSTALL="libudev-dev libglib2.0-dev libsystemd-dev"
  - env:
    - NAME=nautilus
    - REPO=https://gitlab.gnome.org/GNOME/nautilus.git
    - BUILDDEP=nautilus
    - ALSOINSTALL="libgexiv2-dev libseccomp-dev"
    - BUILD="all install"
  - env:
    - NAME=nemo
    - REPO=https://github.com/linuxmint/nemo
    - COMMIT=80672f071742453ec0e84e4a46ec1ab28fe62379
    - BUILDDEP=nemo
    - ALSOINSTALL="libxapp-dev"
    - BUILD="all install"
  - env:
    - NAME=orc
    - REPO=git://anongit.freedesktop.org/gstreamer/orc/
    - BUILDDEP=orc
    - BUILD="all install"
  - env:
    - NAME=outlier
    - REPO=https://github.com/kerolasa/outlier
    - BUILD="all install"
  - env:
    - NAME=pango
    - REPO=https://git.gnome.org/browse/pango/
    - BUILDDEP=pango1.0
    - ALSOINSTALL="libfribidi-dev"
    - BUILD="all install"
  - env:
    - NAME=parzip
    - REPO=https://github.com/jpakkane/parzip
    - BUILD="all install"
    - HACKS='meson wrap update zlib'
  - env:
    - NAME=pipewire
    - REPO=https://github.com/PipeWire/pipewire.git
    - ALSOINSTALL="libdbus-1-dev libasound2-dev libv4l-dev libudev-dev"
    - BUILD="all install"
  - env:
    - NAME=pithos
    - REPO=https://github.com/pithos/pithos
    - BUILDDEP=pithos
    - ALSOINSTALL="libglib2.0-dev"
    - BUILD="all install"
  - env:
    - NAME=polari
    - REPO=https://gitlab.gnome.org/GNOME/polari
    - COMMIT=c97477b23361855e22619546a297d7513163bb76
    - BUILDDEP=polari
    - BUILD="all install"
  - env:
    - NAME=radare2
    - REPO=https://github.com/radare/radare2
    - BUILDDEP=radare2
    - BUILD="all install"
    - HACKS="(cd shlr; ./capstone.sh https://github.com/aquynh/capstone.git next)"
  - env:
    - NAME=sshfs
    - REPO=https://github.com/libfuse/sshfs
    - COMMIT=6cc86fc0bdaaeacfb1bd5e4336f2a2d1e5b189b8
    - BUILDDEP=sshfs
    - BUILD="all install"
  - env:
    - NAME=sysprof
    - REPO=https://git.gnome.org/browse/sysprof
    - BUILDDEP=sysprof
    - ALSOINSTALL="systemd policykit-1"
    - BUILD="all install"
  - env:
    - NAME=systemd
    - REPO=https://github.com/systemd/systemd
    - BUILDDEP=systemd
    - BUILD="all install"
  - env:
    - NAME=szl
    - REPO=https://github.com/dimkr/szl
    - BUILD="all install"
    - HACKS='git submodule update --init'
  - env:
    - NAME=taisei-project
    - REPO=https://github.com/taisei-project/taisei.git
    - ALSOINSTALL="libfreetype6-dev libsdl2-dev libsdl2-image-dev libpng-dev libwebp-dev python-docutils"
    - BUILD="all install"
  - env:
    - NAME=valum
    - REPO=https://github.com/valum-framework/valum
    - ALSOINSTALL="valac libsoup2.4-dev libssl-dev"
    - BUILD="all install"
  - env:
    - NAME=wayland-and-weston
    - REPO=git://anongit.freedesktop.org/wayland/libinput
    - ALSOINSTALL="libudev-dev libmtdev-dev libevdev-dev libwacom-dev doxygen graphviz libgtk-3-dev check valgrind python-sphinx python-sphinx-rtd-theme
      python-recommonmark"
    - BUILD="all install"
  - env:
    - NAME=wlroots
    - REPO=https://github.com/swaywm/wlroots
    - COMMIT=f1fcc685b62d5c37c3b99ce6bfeb11ac1fa59ea6
    - ALSOINSTALL="libegl1-mesa-dev libgbm-dev libgles2-mesa-dev libinput-dev libpixman-1-dev libwayland-dev libxcb-composite0-dev
      libxcb-image0-dev libxkbcommon-dev wayland-protocols"
    - BUILD="all install"
  - env:
    - NAME=xi-gtk
    - REPO=https://github.com/eyelash/xi-gtk
    - ALSOINSTALL="valac libgtk-3-dev libjson-glib-dev"
    - BUILD="all install"
  - env:
    - NAME=xorg
    - REPO=git://anongit.freedesktop.org/xorg/xserver/
    - BUILDDEP=xorg-server
    - BUILD="all install"
  - env:
    - NAME=zstandard
    - REPO=https://github.com/facebook/zstd.git
    - BRANCH=v1.3.4
    - BUILDDEP=zstd
    - SOURCEDIR=contrib/meson
    - BUILD="all install"
python: 3.6
script:
- cat script
- docker run jturney/mesoncorpusci /bin/sh -c "$(cat script)"
services:
- docker

